name: learn_flutter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3            # State management
  go_router: ^14.1.2              # Navigation hiện đại
  get_it: ^7.6.4                  # Dependency Injection
  dio: ^5.3.3                     # Gọi API
  flutter_dotenv: ^5.1.0          # Đa môi trường (.env)
  equatable: ^2.0.5               # So sánh object
  intl: ^0.19.0                   # Định dạng số, tiền, ngày giờ
  cached_network_image: ^3.3.1    # Load ảnh cache
  path_provider: ^2.1.3           # Hỗ trợ lưu trữ file local
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.8.0
  awesome_bottom_bar: ^1.2.4

dev_dependencies:
  build_runner: ^2.4.6            # Tạo code tự động
  json_serializable: ^6.7.1       # Parse JSON
  freezed: ^2.4.5                 # Code generator
  very_good_analysis: ^5.0.0      # Lint chuẩn best practice        # Tạo code tự động cho Hive 
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  assets:
    - .env
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg




  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
